language: node_js
node_js:
  - "8"
script:
  - echo "Deploy!!"
install:
  - npm install -g firebase-tools
after_success:
  - yarn run build
  - firebase deploy --project ronnie-sophie --token $FIREBASE_TOKEN
