language: node_js
node_js:
  - "8"
script:
  - echo "Deploy!!"
install:
  - npm install -g firebase-tools
  - npm install -g react
after_success:
  - yarn run build
after_success:
  - firebase deploy --project ronnie-sophie --token $FIREBASE_TOKEN
