language: node_js
node_js:
  - "8"
script:
  - echo "Deploy!!"
  - npm run build
install:
  - npm install -g firebase-tools
  - npm install
  - npm run build
after_success:
  - firebase deploy --project ronnie-sophie --token $FIREBASE_TOKEN
