language: node_js
node_js:
  - "8"
branches:
  only:
    - master
script:
  - echo "Deploy!!"
  - npm run build
install:
  - npm install -g firebase-tools
  - npm install
after_success:
  - firebase deploy --project ronnie-sophie --token $FIREBASE_TOKEN
