language: node_js
node_js:
  - "8"
script:
  - echo "Deploy!!"
  - yarn build
install:
  - npm install -g firebase-tools
  - npm install -g react
  - npm install -g react-scripts
after_success:
  - firebase deploy --project ronnie-sophie --token $FIREBASE_TOKEN
